
namespace EasyAgendaBase.Enums
{
  public enum TypeMessage
  {
    NEW_USER = 1,
    NEW_APPOINTMENT_CLIENT = 2,
    NEW_APPOINTMENT_PROFESSIONAL = 3,
    APPOINTMENT_CONFIRMATION = 4,
    APPOINTMENT_CANCELLED_CLIENT = 5,
    APPOINTMENT_CANCELLED_PROFESSIONAL = 6,
    RESCHEDULE_APPOINTMENT = 7
  }
}
